export {
  CREATE_CONFIG_MUTATION_EVENTS_SQL,
  CREATE_CONFIG_SNAPSHOTS_SQL,
  CREATE_CONTROL_PLANE_ACTION_EVENTS_SQL,
  CREATE_OPTIMIZATION_RUNS_SQL,
  CREATE_OPTIMIZE_MUTATION_IDEMPOTENCY_SQL,
  CREATE_SCHEMA_MIGRATIONS_SQL,
  CREATE_STORE_METADATA_SQL,
  OBSERVABILITY_SCHEMA_STATEMENTS,
  OBSERVABILITY_SCHEMA_TABLE_DEFINITIONS,
  OBSERVABILITY_SCHEMA_TABLE_NAMES,
  OBSERVABILITY_SCHEMA_VERSION,
  initialObservabilityMetadata
} from "./ostrich/store/schema";
export type {
  ObservabilitySchemaTableName,
  SchemaMetadataRow
} from "./ostrich/store/schema";
